# build a preview of the site (Drafts and Future dates also)

[context.deploy-preview.environment]
  VUE_APP_REALM_ID='programdev-aogmg'
  VUE_APP_S3_ACCESS_KEY_ID='AKIA3HJ74YEF7ELMCCHZ'
  VUE_APP_S3_SECRET_ACCESS_KEY='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'
  VUE_APP_S3_REGION='us-west-1'
  VUE_APP_S3_BUCKET_NAME='pilotcitydev'
  VUE_APP_NODE_ENV = 'development'
  VUE_APP_GRAPHQL_HTTP='https://us-west-2.aws.realm.mongodb.com/api/client/v2.0/app/programdev-aogmg/graphql'
  VUE_APP_STRIPE_CHECKOUT='https://payment-service-dev.api.pilotcity.com/create-checkout-session'
  VUE_APP_STRIPE_INVOICE='https://payment-service-dev.api.pilotcity.com/create-invoice'
  GRAPHQL_API_KEY='izTC1d309E0MmJGq2TQxe1Qmecl6n7LR9RdIUHbo6xsjDgUjsGg47wJMQa29Uw6b'
  PROJECT_TOKEN='wj2a7q7bco'
  VUE_APP_HEAP_ID='2919118384'
  VUE_APP_DISCORD_CLIENT_ID='940141663182024734'
  VUE_APP_DISCORD_CLIENT_SECRET='w7JqyMlm2-dlyzCM44bXpXXWtxp27PpT'
  VUE_APP_DISCORD_JOIN='https://discord-service-dev.api.pilotcity.com/add/user/to/server'
  VUE_APP_DISCORD_REDIRECT='https://develop.pilotcity.com/discordconfirmation'
  VUE_APP_META_GRABBER_ENDPOINT = 'https://url-metadata-grabber-service-dev.api.pilotcity.com/metadata/grabber'
  VUE_APP_ADK_INTERVIEW_ADD_QUESTION='https://videoask-service-dev.api.pilotcity.com/interview/add-question'
  VUE_APP_ADK_INTERVIEW_RE_QUESTION='https://videoask-service-dev.api.pilotcity.com/interview/re-record-question'
  VUE_APP_ADK_INTERVIEW_DEL_QUESTION='https://videoask-service-dev.api.pilotcity.com/delete/question'
  VUE_APP_ADK_INTERVIEW_GENERATE='https://videoask-service-dev.api.pilotcity.com/generate/interview'
  VUE_APP_ADK_INTERVIEW_RESET='https://videoask-service-dev.api.pilotcity.com/interview/reset'
  VUE_APP_ADK_INTERVIEW_FORMDATA='https://videoask-service-dev.api.pilotcity.com/get/form/data'
  VUE_APP_ADK_INTERVIEW_RENAME='https://videoask-service-dev.api.pilotcity.com/interview/change-title'
  VUE_APP_ADK_INTERVIEW_REORDER='https://videoask-service-dev.api.pilotcity.com/interview/change-order'
  VUE_APP_GOOGLE_PLACES='https://google-places-gateway-service-dev.api.pilotcity.com/places/search'
  VUE_APP_GOOGLE_PLACES_DETAILS='https://google-places-gateway-service-dev.api.pilotcity.com/place/details'
  VUE_APP_RESET_EMAIL = 'https://user-service-dev.api.pilotcity.com/reset/password'
  VUE_APP_CLONE_PROGRAM= 'https://program-management-service-dev.api.pilotcity.com'
  VUE_APP_PAYMENT_ENV='development'
  VUE_APP_DOCUSIGN_API_DOMAIN = 'https://docusign-service-dev.api.pilotcity.com/'
  VUE_APP_DOCUSIGN_DOMAIN_URL = 'https://develop.pilotcity.com/'
  APOLLO_KEY= 'https://2346c67dfb8c40deadc7a7c2cf7be667@o528452.ingest.sentry.io" target="_blank" rel="noopener noreferrer">=!=RS9CJp68x9TtyPvJR=!=@o528452.ingest.sentry.io" target="_blank" rel="noopener noreferrer">=!=hr8KgY4fDJ6mGkFGX=!=@o528452.ingest.sentry.io" target="_blank" rel="noopener noreferrer">VUE_APP_SENTRY_DSN==!=de5au7tWtzmK2hhSm=!=@o528452.ingest.sentry.io/5645821'
  VUE_APP_API_ENDPOINT='https://discord-service-dev.api.pilotcity.com/'
  VUE_APP_PREVIEW_MODE_ADKS='scope,train,research'
  VUE_APP_DATADOG_APPLICATIONID='7711f9df-5651-4e13-bc19-c99404570b8e'
  VUE_APP_DATADOG_CLIENT_TOKEN='puba21f9974f0b2fc6ce3d58add6e6d89cc'
  VUE_APP_DATADOG_SERVICE='test_rum'
  VUE_APP_DELETE_ORG='https://user-service-dev.api.pilotcity.com/remove/organizer'
  VUE_APP_ADD_ORGANIZER='https://user-service-dev.api.pilotcity.com/add/organizer'
  VUE_APP_TRAINADK_NEW_BADGE='https://train-service-dev.api.pilotcity.com/train/progress'
  VUE_APP_RESEARCHADK_NEW_BADGE = 'https://research-service-dev.api.pilotcity.com/research/progress'
  VUE_APP_OPENAI_API_KEY='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'
  VUE_APP_VIDASK_SERVICE='https://videoask-service-dev.api.pilotcity.com'
  VUE_APP_GET_RENAME_INVITE='https://videoask-service-dev.api.pilotcity.com/invite/rename-step'
  VUE_APP_GET_DEL_INVITE='https://videoask-service-dev.api.pilotcity.com/invite/delete-step'
  VUE_APP_GET_INVITE_DATA='https://videoask-service-dev.api.pilotcity.com/get/form/data'
  VUE_APP_VERIFY_SLUG='https://videoask-service-dev.api.pilotcity.com/verify-slug'
  VUE_APP_FETCH_INVITE='https://videoask-service-dev.api.pilotcity.com/invite/templates'
  VUE_APP_FETCH_INVITE_LINKS='https://videoask-service-dev.api.pilotcity.com/user-invite-links'
  VUE_APP_GEN_INVITE='https://videoask-service-dev.api.pilotcity.com/generate/invite-link'

[context.deploy-preview]
  command = "NODE_OPTIONS=--max_old_space_size=4096 yarn run build"
  publish = "dist"

[context.master.environment]
  VUE_APP_REALM_ID='program-otolc'
  VUE_APP_S3_ACCESS_KEY_ID='AKIA3HJ74YEF7ELMCCHZ'
  VUE_APP_S3_SECRET_ACCESS_KEY='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'
  VUE_APP_S3_REGION='us-west-1'
  VUE_APP_S3_BUCKET_NAME='pilotcity'
  VUE_APP_NODE_ENV = 'production'
  VUE_APP_PAYMENT_ENV='production'
  VUE_APP_AUTH0='https://authentication-service-prod.api.pilotcity.com/auth0'
  VUE_APP_GRAPHQL_HTTP='https://us-west-2.aws.realm.mongodb.com/api/client/v2.0/app/program-otolc/graphql'
  VUE_APP_STRIPE_CHECKOUT='https://payment-service-prod.api.pilotcity.com/create-checkout-session'
  VUE_APP_STRIPE_INVOICE='https://payment-service-prod.api.pilotcity.com/create-invoice'
  GRAPHQL_API_KEY='f48uTMU0ACoWMaOpU6xsi1AK3aN4r6qad2tuXiNsxbggaHqKmQwdwqIcWXpps8JR'
  PROJECT_TOKEN='wj2a7q7bco'
  VUE_APP_HEAP_ID='166871040'
  VUE_APP_DISCORD_CLIENT_ID='940141663182024734'
  VUE_APP_DISCORD_JOIN='https://discord-service-prod.api.pilotcity.com/add/user/to/server'
  VUE_APP_DISCORD_REDIRECT='https://pilotcity.com/discordconfirmation'
  VUE_APP_DISCORD_CLIENT_SECRET='w7JqyMlm2-dlyzCM44bXpXXWtxp27PpT'
  VUE_APP_ADK_INTERVIEW_ADD_QUESTION='https://videoask-service-prod.api.pilotcity.com/interview/add-question'
  VUE_APP_ADK_INTERVIEW_RE_QUESTION='https://videoask-service-prod.api.pilotcity.com/interview/re-record-question'
  VUE_APP_ADK_INTERVIEW_DEL_QUESTION='https://videoask-service-prod.api.pilotcity.com/delete/question'
  VUE_APP_ADK_INTERVIEW_GENERATE='https://videoask-service-prod.api.pilotcity.com/generate/interview'
  VUE_APP_ADK_INTERVIEW_RESET='https://videoask-service-prod.api.pilotcity.com/interview/reset'
  VUE_APP_ADK_INTERVIEW_FORMDATA='https://videoask-service-prod.api.pilotcity.com/get/form/data'
  VUE_APP_ADK_INTERVIEW_RENAME='https://videoask-service-prod.api.pilotcity.com/interview/change-title'
  VUE_APP_ADK_INTERVIEW_REORDER='https://videoask-service-prod.api.pilotcity.com/interview/change-order'
  VUE_APP_META_GRABBER_ENDPOINT = 'https://url-metadata-grabber-service-prod.api.pilotcity.com/metadata/grabber'
  VUE_APP_DOCUSIGN_API_DOMAIN = 'https://docusign-service-prod.api.pilotcity.com/'
  VUE_APP_RESET_EMAIL = 'https://user-service-prod.api.pilotcity.com/reset/password'
  VUE_APP_DOCUSIGN_DOMAIN_URL = 'https://pilotcity.com/'
  VUE_APP_CLONE_PROGRAM= 'https://program-management-service-prod.api.pilotcity.com'
  APOLLO_KEY= 'service:program:4S-Qv2fgAH5ygRXW8bHluw'
  VUE_APP_GOOGLE_PLACES='https://google-places-gateway-service-prod.api.pilotcity.com/places/search'
  VUE_APP_GOOGLE_PLACES_DETAILS='https://google-places-gateway-service-prod.api.pilotcity.com/place/details'  
  VUE_APP_API_ENDPOINT='https://discord-service-prod.api.pilotcity.com/'
  VUE_APP_PREVIEW_MODE_ADKS='scope,train,research'
  VUE_APP_DATADOG_APPLICATIONID='b414e085-9598-47df-bdde-b953c19f132e'
  VUE_APP_DATADOG_CLIENT_TOKEN='pubf49d9bcd5bf53778ad75f419134186ea'
  VUE_APP_DATADOG_SERVICE='pilotcity.com'
  VUE_APP_DELETE_ORG='https://user-service-prod.api.pilotcity.com/remove/organizer'
  VUE_APP_ADD_ORGANIZER='https://user-service-prod.api.pilotcity.com/add/organizer'
  VUE_APP_TRAINADK_NEW_BADGE='https://train-service-prod.api.pilotcity.com/train/progress'
  VUE_APP_RESEARCHADK_NEW_BADGE = 'https://research-service-prod.api.pilotcity.com/research/progress'
  VUE_APP_OPENAI_API_KEY='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'
  VUE_APP_OPT_IN='https://user-service-prod.api.pilotcity.com/update-airtime-status'

[context.master]
  command = "NODE_OPTIONS=--max_old_space_size=4096 yarn run build"
  publish = "dist"

# build a preview of the site (Drafts and Future dates also)
[context.develop.environment]
  VUE_APP_REALM_ID='programdev-aogmg'
  VUE_APP_S3_ACCESS_KEY_ID='AKIA3HJ74YEF7ELMCCHZ'
  VUE_APP_S3_SECRET_ACCESS_KEY='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'
  VUE_APP_S3_REGION='us-west-1'
  VUE_APP_S3_BUCKET_NAME='pilotcitydev'
  VUE_APP_NODE_ENV = 'development'
  VUE_APP_AUTH0='https://authentication-service-dev.api.pilotcity.com/auth0'
  VUE_APP_GRAPHQL_HTTP='https://us-west-2.aws.realm.mongodb.com/api/client/v2.0/app/programdev-aogmg/graphql'
  VUE_APP_STRIPE_CHECKOUT='https://payment-service-dev.api.pilotcity.com/create-checkout-session'
  VUE_APP_STRIPE_INVOICE='https://payment-service-dev.api.pilotcity.com/create-invoice'
  GRAPHQL_API_KEY='izTC1d309E0MmJGq2TQxe1Qmecl6n7LR9RdIUHbo6xsjDgUjsGg47wJMQa29Uw6b'
  PROJECT_TOKEN='wj2a7q7bco'
  VUE_APP_HEAP_ID='2919118384'
  VUE_APP_DISCORD_CLIENT_ID='940141663182024734'
  VUE_APP_DISCORD_CLIENT_SECRET='w7JqyMlm2-dlyzCM44bXpXXWtxp27PpT'
  VUE_APP_DISCORD_JOIN='https://discord-service-dev.api.pilotcity.com/add/user/to/server'
  VUE_APP_DISCORD_REDIRECT='https://develop.pilotcity.com/discordconfirmation'
  VUE_APP_META_GRABBER_ENDPOINT = 'https://url-metadata-grabber-service-dev.api.pilotcity.com/metadata/grabber'
  VUE_APP_ADK_INTERVIEW_ADD_QUESTION='https://videoask-service-dev.api.pilotcity.com/interview/add-question'
  VUE_APP_ADK_INTERVIEW_RE_QUESTION='https://videoask-service-dev.api.pilotcity.com/interview/re-record-question'
  VUE_APP_ADK_INTERVIEW_DEL_QUESTION='https://videoask-service-dev.api.pilotcity.com/delete/question'
  VUE_APP_ADK_INTERVIEW_GENERATE='https://videoask-service-dev.api.pilotcity.com/generate/interview'
  VUE_APP_ADK_INTERVIEW_RESET='https://videoask-service-dev.api.pilotcity.com/interview/reset'
  VUE_APP_ADK_INTERVIEW_FORMDATA='https://videoask-service-dev.api.pilotcity.com/get/form/data'
  VUE_APP_ADK_INTERVIEW_RENAME='https://videoask-service-dev.api.pilotcity.com/interview/change-title'
  VUE_APP_ADK_INTERVIEW_REORDER='https://videoask-service-dev.api.pilotcity.com/interview/change-order'
  VUE_APP_GOOGLE_PLACES='https://google-places-gateway-service-dev.api.pilotcity.com/places/search'
  VUE_APP_GOOGLE_PLACES_DETAILS='https://google-places-gateway-service-dev.api.pilotcity.com/place/details'
  VUE_APP_RESET_EMAIL = 'https://user-service-dev.api.pilotcity.com/reset/password'
  VUE_APP_CLONE_PROGRAM= 'https://program-management-service-dev.api.pilotcity.com'
  VUE_APP_PAYMENT_ENV='development'
  VUE_APP_DOCUSIGN_API_DOMAIN = 'https://docusign-service-dev.api.pilotcity.com/'
  VUE_APP_DOCUSIGN_DOMAIN_URL = 'https://develop.pilotcity.com/'
  APOLLO_KEY= 'https://2346c67dfb8c40deadc7a7c2cf7be667@o528452.ingest.sentry.io" target="_blank" rel="noopener noreferrer">=!=RS9CJp68x9TtyPvJR=!=@o528452.ingest.sentry.io" target="_blank" rel="noopener noreferrer">=!=hr8KgY4fDJ6mGkFGX=!=@o528452.ingest.sentry.io" target="_blank" rel="noopener noreferrer">VUE_APP_SENTRY_DSN==!=de5au7tWtzmK2hhSm=!=@o528452.ingest.sentry.io/5645821'
  VUE_APP_API_ENDPOINT='https://discord-service-dev.api.pilotcity.com/'
  VUE_APP_PREVIEW_MODE_ADKS='scope,train,research'
  VUE_APP_DATADOG_APPLICATIONID='7711f9df-5651-4e13-bc19-c99404570b8e'
  VUE_APP_DATADOG_CLIENT_TOKEN='puba21f9974f0b2fc6ce3d58add6e6d89cc'
  VUE_APP_DATADOG_SERVICE='test_rum'
  VUE_APP_DELETE_ORG='https://user-service-dev.api.pilotcity.com/remove/organizer'
  VUE_APP_ADD_ORGANIZER='https://user-service-dev.api.pilotcity.com/add/organizer'
  VUE_APP_TRAINADK_NEW_BADGE='https://train-service-dev.api.pilotcity.com/train/progress'
  VUE_APP_RESEARCHADK_NEW_BADGE = 'https://research-service-dev.api.pilotcity.com/research/progress'
  VUE_APP_OPENAI_API_KEY='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'
  VUE_APP_VIDASK_SERVICE='https://videoask-service-dev.api.pilotcity.com'
  VUE_APP_GET_RENAME_INVITE='https://videoask-service-dev.api.pilotcity.com/invite/rename-step'
  VUE_APP_GET_DEL_INVITE='https://videoask-service-dev.api.pilotcity.com/invite/delete-step'
  VUE_APP_GET_INVITE_DATA='https://videoask-service-dev.api.pilotcity.com/get/form/data'
  VUE_APP_VERIFY_SLUG='https://videoask-service-dev.api.pilotcity.com/verify-slug'
  VUE_APP_FETCH_INVITE='https://videoask-service-dev.api.pilotcity.com/invite/templates'
  VUE_APP_FETCH_INVITE_LINKS='https://videoask-service-dev.api.pilotcity.com/user-invite-links'
  VUE_APP_GEN_INVITE='https://videoask-service-dev.api.pilotcity.com/generate/invite-link'
  VUE_APP_OPT_IN='https://user-service-dev.api.pilotcity.com/update-airtime-status'

[context.develop]
  command = "NODE_OPTIONS=--max_old_space_size=4096 yarn run build"
  publish = "dist"
